# PyTorch Fundamentals

Course from Zero to Mastery Learn PyTorch for Deep Learning: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.4.0+cu121


## Introduction to tensors

### Creating tensors
PyTorch tensors are created using `torch.Tensor()`.

In [ ]:
# scalar --> lower case
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# vector --> lower case
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX --> upper case
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0], MATRIX[1]

(tensor([7, 8]), tensor([ 9, 10]))

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR --> upper case
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# Create a random tensor of size (3, 4)
RANDOM_TENSOR = torch.rand(3, 4)
RANDOM_TENSOR

tensor([[0.0010, 0.0837, 0.5279, 0.0140],
        [0.9685, 0.0581, 0.6825, 0.2958],
        [0.0570, 0.0321, 0.3282, 0.7805]])

In [ ]:
# Create a random tensor with similar shape to an image tensor
RND_IMG_SIZE_TENSOR = torch.rand(size = (3, 224, 224)) # color channel, height, width
RND_IMG_SIZE_TENSOR.shape, RND_IMG_SIZE_TENSOR.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
RANDOM_TENSOR.dtype

torch.float32

### Create a range of tensors and tensors-like

In [ ]:
# Use torch.arange()
ONE_TO_TEN = torch.arange(start = 1, end = 11, step = 1)
ONE_TO_TEN

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
TEN_ZEROS = torch.zeros_like(input = ONE_TO_TEN)
TEN_ZEROS

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the three big issues with PyTorch & Deep Learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor
FLOAT_32_TENSOR = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what data type is the tensor (e.g. float 16, float 32, etc.)
                               device = None, # What device is your tensor on? Default is "cpu", but when using GPUs you can change it to "cuda". In order to e.g. multiply two tensors, they need to be on the same device
                               requires_grad = False) # Whether or not to track gradients with this tensors operations
FLOAT_32_TENSOR

tensor([3., 6., 9.])

In [ ]:
FLOAT_32_TENSOR.dtype

torch.float32

In [ ]:
FLOAT_16_TENSOR = FLOAT_32_TENSOR.type(torch.float16)
FLOAT_16_TENSOR

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
# Float 32 tensor
INT_32_TENSOR = torch.tensor([3, 6, 9],
                             dtype = torch.int32,
                             device = None,
                             requires_grad = False)
INT_32_TENSOR

tensor([3, 6, 9], dtype=torch.int32)

### Getting information from tensors

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
# Create a tensor
SOME_TENSOR = torch.rand(size = (3, 4))
SOME_TENSOR

tensor([[0.2548, 0.3848, 0.1609, 0.8018],
        [0.5544, 0.7750, 0.4689, 0.9002],
        [0.3741, 0.8273, 0.7010, 0.8839]])

In [ ]:
# Find out details about some tensor
print(SOME_TENSOR)
print(f"Datatype of tensor: {SOME_TENSOR.dtype}")
print(f"Shape of tensor: {SOME_TENSOR.shape}")
print(f"Device tensor is on: {SOME_TENSOR.device}")

tensor([[0.2548, 0.3848, 0.1609, 0.8018],
        [0.5544, 0.7750, 0.4689, 0.9002],
        [0.3741, 0.8273, 0.7010, 0.8839]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operation)

Tensor operations include:
- Addition
- Subtraction
- Multiplication (element-wise)
- Matrix multiplication
- Division

In [ ]:
# Create a tensor
TENSOR = torch.tensor([1, 2, 3])

# Addition
print(TENSOR + 10) # or use torch.add(TENSOR, 10)

# Mutliplication
print(TENSOR * 10) # or use torch.mul(TENSOR, 10)

# Subtract 10
print(TENSOR - 10)

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])


### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satify:
1. The **inner dimensions** must match
* `(a, b) @ (c, d)` won't work if b \neq d
* `(a, b) @ (b, c)` will work
2. The resulting matrix has the shape of the **outer dimensions**
* `(a, b) @ (b, c)` -> * `(a, c)`

In [ ]:
# Element-wise multiplication
print(TENSOR, "*", TENSOR)
print(f"Equals: {TENSOR * TENSOR}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
print(TENSOR, "dot product", TENSOR)
print(f"Equals: {torch.matmul(TENSOR, TENSOR)}")

tensor([1, 2, 3]) dot product tensor([1, 2, 3])
Equals: 14


In [ ]:
%%time
value = 0
for i in range(len(TENSOR)):
  value += TENSOR[i] * TENSOR[i]

print(value)

tensor(14)
CPU times: user 479 µs, sys: 0 ns, total: 479 µs
Wall time: 487 µs


In [ ]:
%%time
torch.matmul(TENSOR, TENSOR)

CPU times: user 49 µs, sys: 0 ns, total: 49 µs
Wall time: 52 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [ ]:
# Shapes for matrix multiplication
TENSOR_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

TENSOR_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

try:
  print(torch.mm(TENSOR_A, TENSOR_B)) # torch.mm is an alias for torch.matmul
except RuntimeError as e:
  print(f"Runtime error: {e}")

Runtime error: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)


To fix our tensor shape issues, we can maipulate the shape of one of our tensors using the *transpose*

In [ ]:
torch.mm(TENSOR_A, TENSOR_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc. (tensor aggregation)

In [ ]:
# Create a tensor
X = torch.arange(0, 100, 10)
X

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
torch.min(X), X.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(X), X.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 fatatype to work
torch.mean(X.type(torch.float32)), X.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(X), X.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tenseor where the minimum value occurs
X.argmin()

tensor(0)

In [ ]:
# Find the position in tensor that has the maximum value with argmax() -> returns index position of target tenseor where the maximum value occurs
X.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimensions to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way


In [ ]:
# Let's create a tensor
Y = torch.arange(1., 10.)
Y, Y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
try:
  print(Y.reshape(1, 7))
except RuntimeError as e:
  print(f"Runtime error: {e}")

try:
  print(Y.reshape(1, 9))
except RuntimeError as e:
  print(f"Runtime error: {e}")

try:
  print(Y.reshape(9, 1))
except RuntimeError as e:
  print(f"Runtime error: {e}")

try:
  print(Y.reshape(2, 9))
except RuntimeError as e:
  print(f"Runtime error: {e}")

Y_RESHAPED = Y.reshape(1, 9)

Runtime error: shape '[1, 7]' is invalid for input of size 9
tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Runtime error: shape '[2, 9]' is invalid for input of size 9


In [ ]:
# Change the view
Z = Y.view(1,9)
Z, Z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing Z changes X (because a view of a tensor shares the same memory as the original input)
Z[:, 0] = 5
Z, Y

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
Y_STACKED = torch.stack([Y, Y, Y, Y], dim = 0)
Y_STACKED

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
Y_STACKED = torch.stack([Y, Y, Y, Y], dim = 1)
Y_STACKED

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# Squeeze
Y_RESHAPED_SQUEEZED = Y_RESHAPED.squeeze()

print(f"Previous tensor: {Y_RESHAPED}")
print(f"Previous shape: {Y_RESHAPED.shape}")

print(f"\nNew tensor: {Y_RESHAPED_SQUEEZED}")
print(f"New shape: {Y_RESHAPED_SQUEEZED.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# Unsqueeze
Y_RESHAPED_UNSQUEEZED_0 = Y_RESHAPED_SQUEEZED.unsqueeze(dim = 0)  # adds a single dimension to the target tensor at a specific dimension
Y_RESHAPED_UNSQUEEZED_1 = Y_RESHAPED_SQUEEZED.unsqueeze(dim = 1)

print(f"Previous tensor: {Y_RESHAPED_SQUEEZED}")
print(f"Previous shape: {Y_RESHAPED_SQUEEZED.shape}")

print(f"\nNew tensor (dim = 0): {Y_RESHAPED_UNSQUEEZED_0}")
print(f"New shape (dim = 0): {Y_RESHAPED_UNSQUEEZED_0.shape}")

print(f"\nNew tensor (dim = 1): {Y_RESHAPED_UNSQUEEZED_1}")
print(f"New shape (dim = 1): {Y_RESHAPED_UNSQUEEZED_1.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor (dim = 0): tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape (dim = 0): torch.Size([1, 9])

New tensor (dim = 1): tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape (dim = 1): torch.Size([9, 1])


In [ ]:
# Torch.permute - rearranges the dimensions of a target tensor in a specified order
X_ORIGINAL = torch.rand(size = (224, 224, 3)) # height, width, color channel

# Permute the original tensor to reaggrange the axis (or dim) order
X_PERMUTED = X_ORIGINAL.permute(2, 0, 1) # color channel, height, width
X_PERMUTED.shape

torch.Size([3, 224, 224])

**Note:** A permute is a view! Again, a view shares the same memory as the original tensor. Thus, when changing something in the original tensor, this also changes in the permuted version.

In [ ]:
X_ORIGINAL[0, 0, 0] = 10
X_PERMUTED[0, 0, 0]

tensor(10.)

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [ ]:
# Create a tensor
X = torch.arange(1, 10).reshape(1, 3, 3)
X, X.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Index on our new tensor
X[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Index on the middel bracket
X[0][0]

tensor([1, 2, 3])

In [ ]:
# Index on the last bracket
X[0][0][0]

tensor(1)

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
X[:, :, 1]

tensor([[2, 5, 8]])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.
And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* Data as PyTorch tensor, want NumPy -> `torch.Tensor.numpy()`

In [ ]:
# Numpy array to tensor
array = np.arange(1.0, 8.0)
TENSOR = torch.from_numpy(array) # Warning: When converting from numpy to pytorch, pytorch reflects numpy's default datatype (float64), unless specified otherwise

array, TENSOR

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
TENSOR = TENSOR.type(torch.float32)
TENSOR.dtype

torch.float32

In [ ]:
# Change the value of the array, what will happen to `tensor`?
array = array + 1
array, TENSOR

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensor to NumPy array
TENSOR = torch.ones(7)
numpy_tensor = TENSOR.numpy()

In [ ]:
TENSOR, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happens to numpy_tensor?
TENSOR = TENSOR + 1

TENSOR, numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

--> They do not share memory

## Reproducibility (Trying to take the random out of random)

In short how neural networks learns:

`Start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again -> ...``

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
# Create two random tensors

RANDOM_TENSOR_A = torch.rand(3, 4)
RANDOM_TENSOR_B = torch.rand(3, 4)

print(RANDOM_TENSOR_A)
print(RANDOM_TENSOR_B)
print(RANDOM_TENSOR_A == RANDOM_TENSOR_B)

tensor([[0.4985, 0.2801, 0.1541, 0.6753],
        [0.0693, 0.7152, 0.5383, 0.4367],
        [0.8498, 0.4432, 0.5768, 0.2547]])
tensor([[0.5047, 0.9359, 0.4533, 0.8819],
        [0.8827, 0.4414, 0.0987, 0.1570],
        [0.1247, 0.3624, 0.5601, 0.7060]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Random but reproducible tensors

# Set random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
RANDOM_TENSOR_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
RANDOM_TENSOR_D = torch.rand(3, 4)

print(RANDOM_TENSOR_C)
print(RANDOM_TENSOR_D)
print(RANDOM_TENSOR_C == RANDOM_TENSOR_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computations on numbers, thanks to CUDA + NVIDA hardware + PyTorch



### 1. Getting a GPU
1. Google Colab (easiest)
2. Use your own GPU
3. Use cloud computing - GCP, AWS, Azure. These services allow you to rent computers on the cloud and access them.

In [ ]:
!nvidia-smi

Mon Sep  9 15:07:58 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU access with PyTorch

In [ ]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

True

For PyTorch since it is capable of running compute on the GPU or CPU, it is best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

## Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster compuatations.

In [ ]:
# Create a tensor
TENSOR = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(TENSOR, TENSOR.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU if available
TENSOR_on_GPU = TENSOR.to(device)
TENSOR_on_GPU

tensor([1, 2, 3], device='cuda:0')

In [ ]:
# Moving tensors back to CPU
try:
  TENSOR_on_GPU.numpy()
except TypeError as e:
  print(f"TypeError: {e}")

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.


In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = TENSOR_on_GPU.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])