# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
RAND_TENSOR_A = torch.rand(size = (7,7))
RAND_TENSOR_A

tensor([[0.6476, 0.2819, 0.1279, 0.3505, 0.3369, 0.7051, 0.6128],
        [0.7933, 0.7169, 0.2996, 0.4558, 0.8037, 0.4997, 0.3477],
        [0.4871, 0.7900, 0.0230, 0.9613, 0.9950, 0.0957, 0.6894],
        [0.3863, 0.2963, 0.6608, 0.1173, 0.1654, 0.3781, 0.7718],
        [0.2263, 0.3262, 0.2855, 0.2431, 0.6809, 0.8927, 0.0108],
        [0.5424, 0.3820, 0.7109, 0.2174, 0.6224, 0.1279, 0.0108],
        [0.4464, 0.5599, 0.8986, 0.7407, 0.3329, 0.3519, 0.7260]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
RAND_TENSOR_B = torch.rand(size = (1,7))

# Perform matrix multiplication
TENSOR_MM_A = torch.matmul(RAND_TENSOR_A, RAND_TENSOR_B.T)
TENSOR_MM_A

tensor([[1.3689],
        [1.5510],
        [0.9748],
        [1.0950],
        [1.2296],
        [1.1179],
        [1.4116]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
RAND_TENSOR_C = torch.rand(size = (7,7))
RAND_TENSOR_D = torch.rand(size = (1,7))

# Matrix multiply tensors
TENSOR_MM_B = torch.matmul(RAND_TENSOR_C, RAND_TENSOR_D.T)
TENSOR_MM_B, TENSOR_MM_B.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
RANDOM_SEED_GPU = 1234
torch.cuda.manual_seed(RANDOM_SEED_GPU)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
print(torch.cuda.is_available())
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
TENSOR_GPU_A = torch.rand(size = (2,3)).to(device)
TENSOR_GPU_B = torch.rand(size = (2,3)).to(device)

TENSOR_GPU_A, TENSOR_GPU_B

False


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B
TENSOR_MM_GPU = torch.matmul(TENSOR_GPU_A, TENSOR_GPU_B.T)
TENSOR_MM_GPU

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max
print(f"Maximum: {torch.max(TENSOR_MM_GPU)}")

# Find min
print(f"Minimum: {torch.min(TENSOR_MM_GPU)}")

Maximum: 0.5617256760597229
Minimum: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max
print(f"Arg max: {torch.argmax(TENSOR_MM_GPU)}")

# Find arg min
print(f"Arg min: {torch.argmin(TENSOR_MM_GPU)}")

Arg max: 3
Arg min: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
# Set seed
torch.manual_seed(7)

# Create random tensor
RAND_TENSOR_E = torch.rand(size = (1,1, 1, 10))

# Remove single dimensions
RAND_TENSOR_SQUEEZED = RAND_TENSOR_E.squeeze()

# Print out tensors and their shapes
print(RAND_TENSOR_E, RAND_TENSOR_E.shape)
print(RAND_TENSOR_SQUEEZED, RAND_TENSOR_SQUEEZED.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
